# Generated by Django 5.0 on 2023-12-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0003_blogpost_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="date_added",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
