import sys

import pygame

from settings import Settings
from hero import Hero


class Game:
    """Class representing the game with the hero image."""

    def __init__(self):
        """Initialize the game window."""
        pygame.init()
        self.settings = Settings()
        self.screen = pygame.display.set_mode(
            (self.settings.screen_width, self.settings.screen_height))
        pygame.display.set_caption('Game')
        self.hero = Hero(self)

    def run(self):
        """Run the main game loop."""
        while True:
            self._check_events()
            self._update_screen()

    def _check_events(self):
        """Reactions to events generated by mouse or keyboard."""
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                sys.exit()

    def _update_screen(self):
        """Can update the images on the screen and move to new screen."""
        self.screen.fill(self.settings.bg_color)
        self.hero.biltme()
        pygame.display.flip()


if __name__ == '__main__':
    game = Game()
    game.run()
